### ISSUE TITLE
Error Creating MOAI object "Hyperlink"! (CaffeineOS on Pistorm32Lite)

### ISSUE THREAD

**Issue by FabrizioRadica** [BlitterStudio/amidon#4]
Hi, 
I had this error on my A1200 Pistorm32Lite + Rpi3b + CaffeineOS #918
Wifi PCMCIA Connection active and working.

![amidon1 0-error](https://user-images.githubusercontent.com/1652242/229444563-c8e99268-f0e9-4fab-9f3a-e170d2f38475.jpg)

**Comment by dimitris-norce** [comment]
You will need the Hyperlink MUI class installed in your system.
This is already part of MUI 4.0 and MUI 5.0, but it's not included in earlier versions from what I discovered. Unfortunately, the documentation didn't mention that - however, you should be able to copy it into a 3.9 installation from the MUI 4.0 archive.

**Comment by FabrizioRadica** [comment]
CaffeineOS (PiStorm) seems to have MUI3.8 so Hyperlink class it no recognized.
I try to modify the assign with MUI3.9 first and then with 4.0 and see how it behaves.

**Comment by FabrizioRadica** [comment]
Ok now works. :)
You need to use MUI3.9 with libs

Hypertext
TextEditor
NLList
NListTree
NListView
NListViews

**Comment by midwan** [comment]
Thanks for confirming!

I've opened up an issue on the Hollywood forums about the incorrect requirements/missing Hyperlink MUI class as well.

**Comment by FabrizioRadica** [comment]
ah yes... Ibrowse with a fresh MUI3.9 installation, needs NLList.

**Comment by midwan** [comment]
I've updated the Readme to address the missing Hyperlink class issue.
