### ISSUE TITLE
Deserilization Error when using anonymous mode

### ISSUE THREAD

**Issue by rschrewe** [BlitterStudio/amidon#6]
Issue:
When I try to connect to a server (tested with nrw.social and mastodon.social) directly after installation, I first get the code screen for authorisation. When trying to connect to the server, I get the following error message:

![Err1](https://user-images.githubusercontent.com/23267971/232398621-0d239308-9571-477f-81f8-0f2c2d8bf5ce.png)

After selecting ok, amidon dies w/o further messagages.

System Config:

A1000 with pistorm/emu68
AmigaOS 3.2.2
MUI 3.9
Additional Classes & Libs (codesets) as required
AmiSSL 4 & 5

Edit: Typos

**Comment by midwan** [comment]
@rschrewe 
It's not very clear from your description, do you actually login to the server and get the code from your browser to paste it back in Amidon?

**Comment by rschrewe** [comment]
It happens before I can even post the code back to Amidon.

**Comment by midwan** [comment]
@rschrewe 
Wait, that's even more confusing... Amidon is supposed to wait for you to paste the code back, it won't attempt to deserialize anything before that.

Can you describe in detail each step you take please, during that process? Including any buttons you press? I suspect you might be doing something unexpected. :)

**Comment by rschrewe** [comment]
Amidon 1.1 - Clean install

click open settings
click server -> enter nrw.social -> hit return
click Save settings -> browse anonymously
    -> error -> amidon dies

**Comment by rschrewe** [comment]
If I login to a server, it works.

**Comment by midwan** [comment]
Fixed, will be part of the next release
